<a href="https://colab.research.google.com/github/sydoky/NumPyExercies/blob/main/NumPyExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import numpy as np

In [65]:
matrix1 = np.array([1, 2, 3])

In [66]:
matrix1

array([1, 2, 3])

In [67]:
matrix2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [68]:
matrix2

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
matrix3 = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [11, 12, 13],
                    [14, 15, 16]]])

In [70]:
matrix3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [11, 12, 13],
        [14, 15, 16]]])

In [71]:
matrix1.shape #3 columns

(3,)

In [72]:
matrix1.ndim #number of dimensions which means one dimensional 

1

In [73]:
matrix1.dtype

dtype('int64')

In [74]:
matrix1.size #how many values

3

In [75]:
type(matrix1) #my array type is numpy ndarray

numpy.ndarray

In [76]:
matrix2.shape, matrix2.ndim, matrix2.dtype, matrix2.size, type(matrix2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [77]:
matrix3.shape, matrix3.ndim, matrix3.dtype, matrix3.size, type(matrix3) #matrix3.shape ((2, 3, 3)) 2 is tables, 3 is rows in each table, 3 columns in each table

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [78]:
import pandas as pd


In [79]:
dt = pd.DataFrame(matrix2)

In [80]:
dt

0  1  2
0  1  2  3
1  4  5  6

In [81]:
matrix4 = np.ones((10, 2))

In [82]:
matrix4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [83]:
matrix5 = np.zeros((7, 2, 3))

In [84]:
matrix5

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [85]:
matrix11 = np.arange(0,100,3)

In [86]:
matrix11

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [87]:
randomNum = np.random.randint(10,size=(7, 2))

In [88]:
randomNum

array([[6, 3],
       [6, 2],
       [5, 1],
       [9, 8],
       [4, 5],
       [3, 9],
       [6, 8]])

In [89]:
randomFloat = np.random.random((3,5))

In [90]:
randomFloat

array([[0.31800347, 0.11005192, 0.22793516, 0.42710779, 0.81801477],
       [0.86073058, 0.00695213, 0.5107473 , 0.417411  , 0.22210781],
       [0.11986537, 0.33761517, 0.9429097 , 0.32320293, 0.51879062]])

In [91]:
np.random.seed(42)

Misha=np.random.randint(10, size=(4,6))

In [92]:
Misha

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [93]:
rannums = np.random.randint(10, size=(3,7))

In [94]:
rannums

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [95]:
np.unique(rannums)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [96]:
rannums[0] #the zero value is the whole row and not just one number 

array([8, 0, 9, 2, 6, 3, 8])

In [97]:
rannums[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [98]:
phone = np.random.randint(10, size=(3,5))
phone2 = np.ones((3, 5))

In [99]:
phone

array([[4, 1, 3, 6, 7],
       [2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9]])

In [100]:
phone2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
phone + phone2

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [102]:
phone3 = np.ones((5, 3))

In [103]:
phone3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [104]:
phone2.reshape(5, 3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [105]:
phone2.reshape(5, 3) + phone3

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [106]:
myArray = np.ones((3, 5))

In [107]:
myArray

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [108]:
myArray.reshape(5,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [109]:
phone3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [110]:
myArray.reshape(5,3) - phone3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [111]:
myArray.reshape(5,3)*phone3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [112]:
myArray**2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [113]:
np.square(myArray)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [114]:
np.mean(myArray)

1.0

In [115]:
np.max(myArray)

1.0

In [116]:
np.min(myArray)

1.0

In [117]:
np.std(myArray)

0.0

In [118]:
np.var(myArray)

0.0

In [119]:
myArray.reshape(3, 5, 1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [120]:
myArray.T #Transpose is converting rows into columns 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
coffee1 = np.random.randint(10,size=(3,3))
coffee2 = np.random.randint(10,size=(3,2))

In [122]:
coffee1.dot(coffee2) #dot is multiplying 2 arrays together 

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [123]:
coffee3 = np.random.randint(10,size=(4,3))
coffee4 = np.random.randint(10,size=(4,3))

In [124]:
coffee3.dot(coffee4) #it's not gonna work because of the shape . See below how to solve the problem

ValueError: ignored

In [125]:
np.dot(coffee3.T,coffee4)

array([[128, 153, 146],
       [135, 140, 167],
       [ 28,  68,  56]])

In [126]:
prices1 = np.random.randint(10,size=(3,5))
prices2 = np.random.randint(10,size=(3,5))

In [127]:
prices1

array([[7, 1, 0, 6, 6],
       [7, 4, 2, 7, 5],
       [2, 0, 2, 4, 2]])

In [128]:
prices2

array([[0, 4, 9, 6, 6],
       [8, 9, 9, 2, 6],
       [0, 3, 3, 4, 6]])

In [129]:
prices1 > prices2

array([[ True, False, False, False, False],
       [False, False, False,  True, False],
       [ True, False, False, False, False]])

In [130]:
prices1 >= prices2

array([[ True, False, False,  True,  True],
       [False, False, False,  True, False],
       [ True, False, False,  True, False]])

In [131]:
prices1 > 7

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [132]:
prices1 == prices2

array([[False, False, False,  True,  True],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [133]:
np.sort(prices1) #it will be ascending order by default

array([[0, 1, 6, 6, 7],
       [2, 4, 5, 7, 7],
       [0, 2, 2, 2, 4]])

In [134]:
np.sort(prices1)[:,::-1] #it is a descednding way


array([[7, 6, 6, 1, 0],
       [7, 7, 5, 4, 2],
       [4, 2, 2, 2, 0]])

In [135]:
np.argsort(prices1)

array([[2, 1, 3, 4, 0],
       [2, 1, 4, 0, 3],
       [1, 0, 2, 4, 3]])

In [136]:
np.argmax(prices1)

0

In [137]:
np.argmin(prices1)

2

In [138]:
np.argmax(prices1, axis=1)

array([0, 0, 3])

In [139]:
np.argmax(prices1, axis=0)

array([0, 1, 1, 1, 0])

In [140]:
arrayRan = np.random.randint(10, size=(2, 3))

In [141]:
arrayRan

array([[6, 3, 6],
       [2, 5, 1]])

In [152]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])